language: node_js

node_js:
-12.18.3

cache: 
  directories:
    - node_modules

install: 
  -npm ci

services :
  - postgresql

script: 
  # -npm run test:coveralls
  -npm run build
  -npm test
 
# deploy: 
# provider: pages
# skip-cleanup: true
# github-token: $GITHUB_TOKEN
# on:
#   branch: gh-pages